# 첫돌필름 인터뷰형(아기가 직접 말하는) 컨셉 원본 데이터.
# 대사 속 {이름} 같은 칸은 주문마다 질문지 답으로 채운다. 조사(이/가, 은/는)는 채운 뒤 한 번 확인한다.
# build.py가 이 파일과 공통 흐름(FLOW)을 합쳐 interview.json과 마크다운을 만든다.

FIELDS = [
    ("이름", "아기 이름 (성+이름)", "석지구"),
    ("애칭", "부를 때 이름", "지구"),
    ("엄마이름", "엄마 이름", "김유진"),
    ("아빠이름", "아빠 이름", "석우주"),
    ("별명", "집에서 부르는 별명", "감자"),
    ("태어난날", "태어난 날 한마디 (5분용)", "엄마 아빠가 엄청 울었대요"),
    ("기억에남는일", "가장 기억에 남는 일", "제주도 한 달 살기"),
    ("기억한마디", "그 일에 대한 한마디", "바다도 보고 말도 보고, 정말 행복했어요"),
    ("좋아하는놀이", "좋아하는 놀이", "스피너 돌리기"),
    ("특기", "특기 (5분용)", "이유식 300g 완밥"),
    ("좋아하는음식", "좋아하는 음식 (5분용)", "닭고기 고구마죽"),
    ("엄마는", "엄마는 어떤 사람? (한 문장)", "세상에서 제일 다정한 사람이에요"),
    ("아빠는", "아빠는 어떤 사람? (한 문장)", "매일 아침 제 담당이에요"),
    ("가족소개", "형제·반려동물 (5분용, 없으면 비움)", "반려견 두부"),
]

CONCEPTS = [
    {
        "id": "astronaut", "name": "우주인 대원", "show": "지구 귀환 1주년 기자회견",
        "set": "A cute toy-like mission briefing room with a small podium and a few toy microphones, in front of a large round window showing a space station and the blue Earth",
        "outfit": "a tiny white astronaut suit with colorful patches, the helmet resting beside",
        "style": "bright playful sci-fi, soft studio light, clean white and navy palette, cute and cinematic",
        "opener": "The baby floats gently inside a cozy space station cabin among floating toys, then gives a big thumbs-up to the camera.",
        "intro2": "1년간의 지구 탐사 임무를 마치고 돌아왔습니다!",
        "year": ["지구 생활, 생각보다 어려웠어요.", "중력 때문에 걷는 게 제일 힘들었거든요."],
        "q": {"year": "지구 생활 1년, 어땠나요?"},
        "hobby_twist": "우주에서도 이것만큼은 1등이에요!",
        "talent": "특기는 {특기}! 우주인은 체력이 기본이죠.",
        "broll3": ("The baby in the astronaut suit bounces in slow motion in low gravity on a soft moon surface, laughing.", "요즘은 걷기 훈련 중이에요. 거의 다 왔어요!"),
        "broll5": ("The baby looks at the Earth through a round porthole and waves at it.", "지구에서 엄마 아빠를 만나서 정말 다행이에요."),
        "dol": "우주 최고의 선택을 보여 드릴게요!",
        "closing": "오늘 임무 완료! 밥은 꼭 드시고 가세요~",
    },
    {
        "id": "doctor", "name": "소아과 의사", "show": "1년 건강검진 결과 발표",
        "set": "A bright, cheerful pediatric clinic room with a small desk, toy medical tools and colorful pictures on the wall",
        "outfit": "a tiny white doctor's coat with a toy stethoscope around the neck",
        "style": "bright clean pastel clinic, soft window light, warm and friendly, cute cinematic",
        "opener": "The baby in a tiny doctor's coat listens to a teddy bear's chest with a toy stethoscope very seriously, then nods.",
        "intro2": "오늘은 제 1년 건강검진 결과를 발표하겠습니다.",
        "year": ["키도 쑥쑥, 몸무게도 쑥쑥!", "진단 결과, 귀여움 수치가 정상 범위를 넘었습니다."],
        "q": {"year": "1년 동안 건강은 어땠나요?", "name": "환자분, 아니 선생님 성함이요?"},
        "hobby_twist": "스트레스 해소에 최고예요.",
        "talent": "특기는 {특기}! 의사 선생님도 인정했어요.",
        "broll3": ("The baby checks a teddy bear's temperature with a toy thermometer and puts a small bandage on its arm.", "요즘은 곰돌이 환자를 돌보고 있어요."),
        "broll5": ("The baby stands next to a colorful height chart on the wall, stretching up on tiptoes.", "1년 만에 이만큼이나 컸답니다!"),
        "dol": "청진기를 잡으면 진짜 의사가 되는 걸까요?",
        "closing": "처방전 드려요. 맛있게 드시고 많이 웃기!",
    },
    {
        "id": "anchor", "name": "뉴스 앵커", "show": "첫돌 특집 뉴스",
        "set": "A professional TV news studio with a sleek anchor desk, blue studio lights and blurred monitors in the background",
        "outfit": "a tiny navy suit and tie",
        "style": "polished broadcast studio look, crisp lighting, blue and white palette, playful and cute",
        "opener": "The baby sits at the news anchor desk, taps a stack of papers on the desk seriously, then looks up at the camera like a playful little host.",
        "intro1": "속보입니다! 오늘 한 아기가 첫 생일을 맞았습니다.",
        "intro2": "저는 돌잔치 현장의 {이름} 앵커입니다.",
        "year": ["올해 가장 뜨거운 뉴스는 바로 저였죠.", "하루하루가 특종이었습니다."],
        "q": {"name": "현장 인터뷰, 이름이 어떻게 되시죠?", "year": "올 한 해를 돌아본다면요?"},
        "hobby_twist": "이건 단독 보도입니다!",
        "talent": "특기는 {특기}! 방금 들어온 소식이에요.",
        "broll3": ("The baby, as a field reporter in a tiny trench coat, holds a big microphone outdoors in a sunny park.", "현장에 나와 있는 {애칭} 기자입니다!"),
        "broll5": ("The baby points at a weather map full of bright suns and fluffy clouds.", "오늘 돌잔치 날씨는 맑음, 행복 지수는 최고!"),
        "dol": "결과는 잠시 후 생중계로 전해 드립니다!",
        "closing": "이상 {애칭} 앵커였습니다. 식사 꼭 하고 가세요~",
    },
    {
        "id": "idol", "name": "아이돌 데뷔", "show": "데뷔 쇼케이스",
        "set": "A glittering showcase stage with pink and purple spotlights and a small microphone stand",
        "outfit": "a sparkly stage outfit with a tiny headset microphone",
        "style": "playful kids' stage show look, colorful stage lighting, glitter and lens flares, cute and energetic",
        "opener": "The baby stands on stage under colorful spotlights and does a cute little dance, arms waving, as confetti falls.",
        "intro2": "연습생 기간 1년, 드디어 오늘 데뷔합니다!",
        "year": ["매일 밤낮 없이 연습했어요.", "새벽 연습은 엄마 아빠가 더 힘들었대요."],
        "q": {"year": "연습생 1년, 어땠어요?"},
        "hobby_twist": "제 무대의 킬링 파트예요!",
        "talent": "특기는 {특기}! 제 필살기예요.",
        "broll3": ("In a practice room with big mirrors, the baby in a tiny tracksuit bounces to music.", "안무 연습은 하루도 빼먹지 않았어요!"),
        "broll5": ("The baby signs a big photo card with a crayon, very focused, tongue slightly out.", "팬 사인회도 준비했답니다."),
        "dol": "마이크를 잡으면 진짜 가수 데뷔일까요?",
        "closing": "여러분 사랑해요! 식사 꼭 하고 가세요~",
    },
    {
        "id": "chef", "name": "꼬마 셰프", "show": "첫돌 특선 코스 인터뷰",
        "set": "A warm restaurant kitchen with copper pots, fresh vegetables and a small wooden counter",
        "outfit": "a tiny white chef jacket and a tall chef hat",
        "style": "warm cozy kitchen, golden light, appetizing colors, cute cinematic food-show look",
        "opener": "The baby in a chef hat tastes something from a wooden spoon, closes the eyes and makes an OK sign with the fingers.",
        "intro2": "오늘을 위해 첫돌 특선 코스를 준비했습니다.",
        "year": ["1년 동안 세상의 모든 맛을 연구했어요.", "이유식부터 간식까지, 미식 인생 시작이죠."],
        "q": {"food": "셰프의 추천 메뉴는요?"},
        "food": "제 추천 메뉴는 {좋아하는음식}! 강력 추천해요.",
        "hobby_twist": "요리하다 쉴 때 최고예요.",
        "talent": "특기는 {특기}! 셰프는 먹는 것도 실력이죠.",
        "broll3": ("The baby stirs a small pot with a big spoon while steam rises, cheeks puffed in concentration.", "오늘도 정성을 가득 담았어요."),
        "broll5": ("The baby carefully places colorful vegetables on a tiny plate like plating a fine dish.", "플레이팅도 신경 썼답니다."),
        "dol": "주걱을 잡을까요? 그건 비밀이에요!",
        "closing": "오늘의 코스, 맛있게 드시고 가세요~",
    },
    {
        "id": "athlete", "name": "국가대표 선수", "show": "금메달 기자회견",
        "set": "A stadium medal-ceremony backdrop with bright lights and a blurred cheering crowd",
        "outfit": "a tiny national-team tracksuit with a shiny gold medal",
        "style": "sporty stadium look, bright energetic lighting, bold colors, cute and triumphant",
        "opener": "The baby crawls fast along a mini running track, breaks through a ribbon at the finish line and raises both arms.",
        "intro2": "뒤집기 종목 국가대표, 금메달리스트입니다!",
        "year": ["정말 강도 높은 훈련을 했어요.", "뒤집기, 배밀이, 잡고 서기까지 전 종목 석권!"],
        "q": {"year": "금메달까지의 1년, 어땠나요?"},
        "hobby_twist": "이 종목만큼은 세계 신기록이에요.",
        "talent": "특기는 {특기}! 매일 훈련한 결과죠.",
        "broll3": ("The baby lifts a tiny toy dumbbell with a determined face.", "근력 운동도 빼놓지 않았어요."),
        "broll5": ("The baby bites the gold medal like a little champion and grins.", "금메달은 역시 깨물어 봐야죠!"),
        "dol": "오늘 돌잡이도 금메달 따러 갑니다!",
        "closing": "응원 감사합니다! 식사 꼭 하고 가세요~",
    },
    {
        "id": "pilot", "name": "비행기 기장", "show": "첫돌행 기내 방송",
        "set": "An airplane cockpit with softly glowing instrument panels and fluffy clouds outside the windshield",
        "outfit": "a tiny pilot uniform and a captain's hat",
        "style": "bright aviation look, sunny sky light, clean blue and gold palette, cute cinematic",
        "opener": "The baby in a captain's hat flips switches in the cockpit, looks out at the clouds, then salutes the camera.",
        "intro1": "승객 여러분, 기장 {이름}입니다.",
        "intro2": "이 비행기는 첫 번째 생일로 향합니다.",
        "year": ["지난 1년, 약간의 난기류가 있었지만", "엄마 아빠 부기장과 무사히 비행했어요."],
        "q": {"name": "기장님, 자기소개 부탁드려요!", "year": "1년 비행, 어떠셨어요?"},
        "hobby_twist": "비행 중 최고의 기분 전환이죠.",
        "talent": "특기는 {특기}! 기장의 필수 능력이에요.",
        "broll3": ("The baby waves from a round airplane window with clouds and sunshine outside.", "창밖 풍경, 정말 멋지죠?"),
        "broll5": ("The baby pushes a tiny snack cart down a toy airplane aisle.", "기내 간식 서비스도 제가 직접!"),
        "dol": "곧 돌잡이 공항에 착륙합니다. 목적지는 비밀!",
        "closing": "승객 여러분, 즐거운 식사 되십시오~",
    },
    {
        "id": "ceo", "name": "꼬마 대표이사", "show": "창립 1주년 주주총회",
        "set": "A luxurious executive office with a big wooden desk, a leather chair and a city skyline window",
        "outfit": "a tiny suit and tie holding a toy smartphone",
        "style": "sleek corporate office look, warm afternoon light, rich wood tones, cute and confident",
        "opener": "The baby CEO spins slowly in a big leather office chair, stops, and points at the camera confidently.",
        "intro2": "{애칭} 주식회사 창립 1주년에 오신 걸 환영합니다!",
        "year": ["올해 실적을 발표하겠습니다.", "몸무게 세 배 성장, 웃음은 무한 성장!"],
        "q": {"year": "올해 실적은 어땠나요?"},
        "hobby_twist": "회사의 핵심 복지예요.",
        "talent": "특기는 {특기}! 우리 회사 핵심 역량이죠.",
        "broll3": ("The baby points at a whiteboard with a big hand-drawn rising arrow and a heart.", "내년 목표는 걷기, 말하기 동시 상장!"),
        "broll5": ("The baby signs a paper with a big crayon and stamps it proudly.", "중요한 결재도 제가 직접 합니다."),
        "dol": "오늘 돌잡이는 최대 투자 결정입니다!",
        "closing": "배당은 맛있는 식사로 드릴게요~",
    },
    {
        "id": "detective", "name": "꼬마 탐정", "show": "1년 사건 파일 브리핑",
        "set": "A cozy vintage detective office with a desk lamp, a magnifying glass and a corkboard with photos connected by red string",
        "outfit": "a tiny checkered deerstalker hat and a trench coat",
        "style": "warm vintage mystery look, amber lamp light, cozy and playful, cute cinematic",
        "opener": "The baby detective peers at the camera through a big magnifying glass, one eye looking huge, then gasps.",
        "intro2": "1년 동안 우리 집 사건을 해결해 왔습니다.",
        "year": ["첫 번째 사건, 사라진 아빠의 잠!", "범인은… 바로 저였죠."],
        "q": {"year": "올해 가장 큰 사건은요?"},
        "hobby_twist": "추리할 때 집중력이 올라가요.",
        "talent": "특기는 {특기}! 탐정의 기본기입니다.",
        "broll3": ("The baby crawls on the floor following tiny footprints with a magnifying glass.", "사라진 간식 사건도 제가 해결했어요."),
        "broll5": ("The baby pins a photo on a corkboard and connects it with red string, nodding seriously.", "모든 단서는 사랑으로 이어져 있었어요."),
        "dol": "마지막 미스터리, 정답은 곧 공개됩니다!",
        "closing": "사건 종결! 모두 식사하고 가세요~",
    },
    {
        "id": "creator", "name": "꼬마 크리에이터", "show": "첫돌 감사 라이브",
        "set": "A colorful streaming room with a ring light, a big studio microphone and neon heart lights",
        "outfit": "a tiny hoodie and oversized headphones",
        "style": "bright streamer room look, colorful neon and ring light, lively and cute",
        "opener": "The baby adjusts oversized headphones, leans toward a big microphone and waves at the camera as if starting a live stream.",
        "intro1": "구독자 여러분, 안녕하세요!",
        "intro2": "첫돌 기념 감사 라이브, 지금 시작합니다!",
        "year": ["영상 찍고, 사진 찍고… 정말 바빴어요.", "인생 첫 1년, 조회수 폭발이었죠."],
        "q": {"year": "크리에이터 1년 차, 어땠어요?"},
        "hobby_twist": "제 채널 인기 콘텐츠예요!",
        "talent": "특기는 {특기}! 구독자들이 제일 좋아해요.",
        "broll3": ("The baby excitedly unboxes a gift box in front of the camera, pulling out colorful ribbons.", "오늘은 특별히 선물 언박싱도 준비했어요!"),
        "broll5": ("The baby looks at a tablet screen full of hearts and giggles.", "댓글 하나하나 다 보고 있어요!"),
        "dol": "결과는 이 방송에서 최초 공개합니다!",
        "closing": "구독, 좋아요, 그리고 식사 꼭 하세요~",
    },
]
