# 첫돌필름 Google Flow 프롬프트 원본 데이터.
# tier: 1 = 1분·3분·5분 모두 사용, 3 = 3분·5분, 5 = 5분만.
# 이 파일을 고친 뒤 `python3 build.py`를 실행하면 prompts.json과 마크다운이 다시 만들어진다.

CONCEPTS = [
    {
        "id": "fairy",
        "name": "동화 속 첫 생일",
        "mood": "몽환, 파스텔",
        "style": "soft pastel fairytale world, dreamy volumetric light, gentle bokeh, storybook cinematic look, warm and magical",
        "clips": [
            (1, "구름 위의 성", "분홍 구름 위에 떠 있는 성, 창문으로 다가감",
             "Wide establishing shot of a pastel castle floating on fluffy pink clouds at sunrise, tiny sparkles drifting through the air. Slow aerial push-in toward a round castle window."),
            (5, "창가에서 깨어나는 아기", "별무늬 이불 침대에서 눈 비비며 웃음",
             "Medium shot through a round castle window: the baby wakes up in a soft canopy bed with star-patterned blankets, rubs the eyes and smiles at the morning light. Slow dolly-in."),
            (1, "요정 친구 등장", "빛나는 요정 셋이 날아와 아기 손에 반짝이",
             "Close-up: three tiny glowing fairies with translucent wings flutter around the baby; the baby reaches out and giggles as sparkles land on the baby's hand. Shallow depth of field."),
            (3, "요정의 선물 망토", "반짝이 망토와 꽃 왕관을 씌워 줌",
             "The fairies drape a tiny glittering cape over the baby's shoulders and place a small flower crown on the baby's head; the baby looks up in wonder. Gentle orbit camera."),
            (5, "구름 정원 산책", "커다란 빛나는 꽃 사이를 기어감",
             "The baby crawls along a path of soft cloud through a garden of oversized glowing flowers and floating bubbles, fairies leading the way. Low tracking shot at the baby's eye level."),
            (3, "무지개 미끄럼틀", "무지개 미끄럼틀을 타고 구름 쿠션으로",
             "The baby slides gently down a short pastel rainbow slide into a pile of cloud pillows, laughing while the fairies clap. Slow motion, side angle."),
            (5, "아기 유니콘", "하얀 아기 유니콘이 다가와 비빔",
             "A fluffy white baby unicorn trots up and nuzzles the baby; the baby pats its soft mane and smiles. Warm backlight, medium shot."),
            (1, "파티장 입장", "구름을 타고 풍선 가득한 성 홀로",
             "The baby rides a small floating cloud into a grand castle hall decorated with pastel balloons, ribbons and fairy lights while confetti drifts down. Wide shot, slow crane down."),
            (5, "빛나는 선물 상자", "상자에서 별빛이 쏟아짐",
             "Close-up of the baby opening a small glowing gift box; golden light and tiny stars float out and reflect on the baby's delighted face."),
            (1, "생일 케이크", "숫자 1 초가 꽂힌 파스텔 케이크",
             "A tall pastel birthday cake with a single candle shaped like the number 1 is placed in front of the baby; candlelight glows on the baby's face as fairies gather around. Slow push-in."),
            (1, "촛불 끄기", "후~ 불자 반짝이와 꽃가루가 터짐",
             "The candle flame goes out with a gentle puff and a burst of sparkles and confetti fills the air while the fairies cheer around the baby. Medium close-up."),
            (5, "요정들과 춤", "떠 있는 등불 아래 빙글빙글",
             "The fairies and the baby dance in a circle on the cloud floor under floating lanterns; the baby bounces happily. Circular tracking shot."),
            (3, "별빛 마차", "나비가 끄는 수정 마차로 밤하늘 비행",
             "The baby rides in a small crystal carriage pulled by glowing butterflies, flying over the castle into a twilight sky. Wide aerial tracking shot."),
            (5, "별 따기", "마차 창밖으로 손을 뻗어 별을 잡음",
             "From the carriage window the baby reaches up and catches a small shining star, holding it with both hands as it glows softly. Close-up."),
            (3, "꿈나라로", "별 인형을 안고 하품",
             "Back in the canopy bed, the baby hugs a star-shaped plush and yawns while the fairies pull up a moonlight blanket. Soft night lighting, slow dolly-out."),
            (1, "엔딩", "별밤의 성, 제목 넣을 빈 공간",
             "Wide shot of the floating castle under a starry night sky with a big crescent moon; the camera slowly pulls back into the clouds, leaving empty space in the lower third for a title."),
        ],
    },
    {
        "id": "hanbok",
        "name": "한복 돌잔치",
        "mood": "전통, 따뜻함",
        "style": "warm natural morning light, traditional Korean aesthetics, soft film grain, elegant and heartfelt, rich red and gold accents",
        "clips": [
            (1, "한옥 마당의 아침", "처마 사이 햇살, 등과 비단 깃발",
             "Wide establishing shot of a traditional Korean hanok courtyard in the morning, sunlight falling through the eaves, paper lanterns and a colorful silk banner swaying gently. Slow crane down."),
            (5, "색동저고리", "마루 위에 놓인 색동 한복과 굴레",
             "Close-up of a small saekdong hanbok with rainbow-striped sleeves and a tiny traditional baby hat (gulle) laid on a wooden floor, dust sparkling in the sunbeams. Slow slide."),
            (1, "한복 입은 아기", "비단 방석에 앉아 카메라 보며 웃음",
             "Medium shot: the baby wearing a colorful saekdong hanbok and a gulle hat sits on a silk cushion on the wooden maru floor, smiling at the camera. Gentle push-in."),
            (3, "첫걸음", "어른 손가락 잡고 마루를 걸음(손만 보임)",
             "The baby toddles a few steps across the wooden maru holding an adult's fingers, only the adult's hands visible, hanbok sleeves fluttering. Low tracking shot."),
            (5, "전통 놀잇감", "팽이와 복주머니로 놀기",
             "The baby plays with a traditional wooden spinning top and colorful silk pouches on a woven mat, laughing. Top-down shot."),
            (1, "돌상", "떡과 과일탑이 차려진 돌상 앞",
             "Wide shot of a traditional first-birthday table (doljanchi) piled with rice cakes and fruit towers in front of a red folding screen; the baby sits before it on a silk cushion. Slow dolly-in."),
            (3, "돌잡이 물건", "실, 연필, 마이크, 청진기, 복주머니",
             "Close-up of doljabi items arranged on a tray: a skein of thread, a pencil, a microphone, a stethoscope and a small coin pouch. Slow focus pull across them."),
            (1, "돌잡이!", "하나를 번쩍 잡아 들고 까르르",
             "The baby reaches forward, firmly grabs one item from the tray, lifts it high and giggles while flower petals fall. Medium close-up, slow motion."),
            (5, "가족들의 박수", "흐릿한 가족들 박수, 아기만 선명",
             "Blurred family members in hanbok clap and laugh in the background while the baby, in sharp focus, looks around proudly."),
            (3, "큰절", "두 손 모아 서툰 절",
             "The baby in hanbok bows clumsily on the cushion in a traditional greeting with both hands together. Warm backlight, side angle."),
            (5, "무지개떡", "무지개떡을 오물오물",
             "Close-up of the baby holding a small colorful layered rice cake (mujigae tteok) and taking a messy, happy bite."),
            (5, "매화나무 아래", "떨어지는 꽃잎을 잡으려 손 뻗음",
             "The baby sits under a blooming plum tree in the courtyard as pink petals drift down, reaching for them. Slow motion."),
            (3, "등불 켜진 저녁", "등불을 신기하게 바라봄",
             "Evening: paper lanterns glow in the courtyard while the baby in hanbok sits on the maru gazing at them in wonder. Warm golden light, slow orbit."),
            (5, "수복 베개", "수놓은 비단 베개 위의 작은 손",
             "Close-up of the baby's small hand resting on an embroidered silk pillow with a traditional longevity pattern, the light gently shifting."),
            (1, "손 흔들기", "소매를 흔들며 활짝 웃음",
             "The baby waves both hands at the camera in the courtyard, hanbok sleeves swinging, with a big smile. Medium shot, slight push-in."),
            (1, "엔딩", "노을 속 한옥 지붕, 제목 공간",
             "Wide shot of the hanok courtyard at dusk with glowing lanterns; the camera slowly rises above the roof tiles into a clear sky, leaving space in the center for a title."),
        ],
    },
    {
        "id": "space",
        "name": "우주 탐험 첫돌",
        "mood": "신비, 모험",
        "style": "whimsical storybook space adventure, soft glowing colors, cute rounded toy-like spaceship, cinematic but gentle, nothing scary",
        "clips": [
            (1, "발사대", "장난감 같은 로켓, 카운트다운 불빛",
             "Wide shot of a small round white-and-orange toy-like rocket on a launch pad at dawn, steam puffing and a countdown light blinking. Slow push-in."),
            (5, "조종석", "우주복(헬멧 없음) 입고 버튼 누르기",
             "Inside a cozy round cockpit with soft padded walls, the baby sits in a plush seat wearing a tiny astronaut jumpsuit without a helmet, pressing big colorful buttons and giggling."),
            (1, "이륙", "파스텔 구름 꼬리를 남기며 발사",
             "The rocket lifts off gently, leaving a trail of pastel clouds as it rises into a starry sky. Wide shot, camera tilts up."),
            (3, "창밖의 지구", "창에 손 대고 지구를 바라봄",
             "Through the round cockpit window the baby presses both hands on the glass, looking at the glowing blue Earth below. Over-the-shoulder shot, then the baby's amazed face."),
            (1, "무중력", "장난감과 함께 둥둥",
             "Zero gravity: the baby floats softly inside the cabin while toys and a small plush moon drift around; the baby laughs and reaches for them. Slow orbit shot."),
            (5, "로봇 친구", "동그란 로봇이 별 쿠키를 건넴",
             "A friendly little round robot with glowing eyes waves at the baby and offers a floating star-shaped cookie. Medium shot."),
            (3, "고리 행성", "파스텔 고리 행성 옆을 지나감",
             "Wide shot of the rocket flying past a planet with pastel rings and sparkling ice while stars twinkle. Tracking shot."),
            (5, "혜성", "창밖을 지나는 무지개 혜성",
             "Close-up of the baby watching colorful comets streak past the window, eyes following them, mouth open in wonder."),
            (1, "달 착륙", "부드럽게 착륙, 먼지가 천천히",
             "The rocket lands softly on a glowing moon surface with small craters while dust puffs up in slow motion. Wide shot."),
            (3, "달 위의 첫걸음", "헬멧 없는 동화풍, 작은 발자국",
             "Storybook-style moon walk without a helmet: the baby toddles across the soft moon surface leaving tiny footprints, the Earth in the sky behind. Low tracking shot."),
            (5, "깃발 꽂기", "숫자 1 깃발을 꽂고 박수",
             "The baby plants a small flag with a big number 1 on it into the moon surface and claps. Medium shot."),
            (5, "통통 점프", "낮은 중력에서 통통 튀어 오름",
             "The baby bounces in low gravity, floating up a little with each step and landing softly while giggling. Side angle, slow motion."),
            (3, "케이크 별자리", "별들이 이어져 케이크 모양 별자리",
             "Stars connect with lines of light to form a constellation shaped like a birthday cake while the baby points up at it. Wide shot, camera tilts up."),
            (5, "달 돌멩이", "반짝이는 달 돌을 두 손으로",
             "Close-up of the baby holding a glowing moon rock that sparkles in the baby's hands."),
            (1, "우주 생일 파티", "로봇 친구와 숫자 1 초 케이크",
             "Back in the cabin, the baby sits before a small birthday cake with a single candle shaped like the number 1 while the robot friend claps; stars shine outside the window. Medium shot."),
            (1, "엔딩", "하트 궤적을 그리며 지구로",
             "Wide shot of the rocket flying toward Earth through a field of stars, its glowing trail curling into a heart shape, leaving empty space for a title."),
        ],
    },
    {
        "id": "seasons",
        "name": "사계절 성장 여행",
        "mood": "감성, 자연광",
        "style": "natural cinematic look, soft golden-hour light, gentle film grain, true-to-life colors, heartfelt family documentary feel",
        "clips": [
            (1, "봄 · 벚꽃 피크닉", "벚꽃 아래 돗자리, 꽃잎이 흩날림",
             "Spring: the baby sits on a picnic blanket under blooming cherry blossom trees as petals fall. Wide shot, slow push-in."),
            (5, "코끝의 꽃잎", "꽃잎이 코에 내려앉아 까르르",
             "Close-up: a cherry blossom petal lands on the baby's nose; the baby blinks and laughs."),
            (3, "봄 · 꽃길 유모차", "개나리와 튤립 길을 지나감",
             "Spring: the baby rides in a stroller along a path lined with yellow forsythia and tulips, looking around curiously. Side tracking shot."),
            (5, "봄비", "노란 우비, 창문의 빗방울 만지기",
             "Spring rain: the baby in a tiny yellow raincoat watches raindrops on a window and touches the glass. Close-up, soft light."),
            (1, "여름 · 바닷가", "모자 쓰고 파도에 발가락",
             "Summer: the baby sits on the sand of a calm beach in a sun hat while gentle waves touch the baby's toes; the baby squeals with joy. Low angle, slow motion."),
            (3, "여름 · 물놀이", "마당 풀장에서 오리 인형과 첨벙",
             "Summer: the baby splashes in a small inflatable pool with rubber ducks in a sunny backyard. Top-down shot."),
            (5, "여름밤 반딧불", "마루에서 반딧불에 손 뻗기",
             "Summer night: fireflies glow around the baby sitting on a wooden porch; the baby reaches toward one glowing firefly. Warm dusk light."),
            (5, "수박", "볼에 수박즙 묻히고 싱글벙글",
             "Summer: close-up of the baby eating a slice of watermelon, juice on the cheeks, grinning."),
            (1, "가을 · 단풍", "단풍 더미에서 잎을 던지며 놀기",
             "Autumn: the baby sits in a pile of orange and red maple leaves in a park, throwing leaves into the air. Medium shot, slow motion."),
            (3, "가을 · 억새밭", "노을 속 억새 사이를 기어감",
             "Autumn: the baby in a knitted sweater crawls through a field of golden pampas grass at sunset. Low tracking shot, backlight."),
            (5, "도토리", "도토리와 단풍잎을 진지하게 관찰",
             "Autumn: close-up of the baby holding a big shiny acorn and a red leaf, examining them seriously."),
            (1, "겨울 · 첫눈", "처음 보는 눈을 손과 입으로 받기",
             "Winter: the baby in a fluffy snowsuit sees falling snow for the first time, catching snowflakes with open hands and mouth. Medium close-up, slow motion."),
            (3, "겨울 · 눈사람", "작은 눈사람을 장갑 낀 손으로 토닥",
             "Winter: the baby sits next to a tiny snowman with a carrot nose, patting it with mittens. Wide shot, soft blue light."),
            (5, "겨울밤 창가", "눈 오는 창가에서 곰 인형 안기",
             "Winter night: the baby sits by a window with warm indoor lights and snow falling outside, hugging a plush bear. Slow dolly-in."),
            (1, "첫 생일", "사계절 소품에 둘러싸인 숫자 1 케이크",
             "A year later: the baby sits before a birthday cake with a number 1 candle, surrounded by small decorations of all four seasons: cherry blossoms, a seashell, a maple leaf and a snowflake. Warm indoor light, slow push-in."),
            (1, "엔딩 · 한 그루 나무", "뒤의 나무가 봄→겨울로 변함",
             "One continuous shot: the same tree behind the smiling baby changes through spring, summer, autumn and winter, ending with empty space for a title."),
        ],
    },
    {
        "id": "submarine",
        "name": "바닷속 잠수함 모험",
        "mood": "청량, 신기함",
        "style": "bright whimsical underwater adventure seen from inside a cute submarine, clear turquoise water, soft caustic light patterns, storybook colors, no scary creatures",
        "clips": [
            (1, "노란 잠수함", "잔잔한 바다에서 거품과 함께 잠수",
             "Wide shot of a small round yellow submarine with big porthole windows bobbing on a calm turquoise sea, then gently diving under the surface with bubbles. Slow push-in."),
            (5, "잠수함 안", "줄무늬 세일러복, 작은 핸들 돌리기",
             "Inside a cozy submarine cabin with brass details and soft cushions, the baby in a little striped sailor outfit turns a small toy steering wheel and giggles."),
            (1, "창밖의 고래", "둥근 창에 손 대고 고래를 봄",
             "Close-up of the baby with both hands on a big round porthole as a friendly smiling whale swims past outside, the baby's face lit by blue light."),
            (3, "물고기 떼", "알록달록 물고기가 소용돌이",
             "Outside the porthole a school of colorful tropical fish swirls in a spiral while the baby follows them with wide eyes. Over-the-shoulder shot."),
            (5, "아기 거북", "거북이 지느러미로 인사, 아기도 손 흔듦",
             "A baby sea turtle swims close to the window and seems to wave a flipper; the baby waves back. Medium close-up."),
            (3, "산호초", "햇살 비치는 산호초 위를 지나감",
             "Wide shot of the submarine gliding over a vibrant coral reef with anemones and sea stars, sunbeams falling from above. Tracking shot."),
            (5, "문어 친구", "파스텔 문어가 유리를 톡톡",
             "A curious pastel-colored octopus gently taps the glass; the baby taps back and laughs. Close-up."),
            (1, "산호 궁전", "조개 탑과 진주 조명의 궁전 도착",
             "The submarine arrives at a glowing coral palace with seashell towers and pearl lights. Wide shot, slow crane."),
            (5, "거품 돔", "커다란 조개 쿠션에 앉아 거품 구경",
             "Inside a large air-filled bubble dome in the coral palace, the baby sits on a giant seashell cushion while bubbles float around. Medium shot."),
            (3, "진주 놀이", "빛나는 진주를 두 손으로 굴림",
             "Close-up of the baby rolling a big shiny glowing pearl between both hands."),
            (1, "바닷속 생일 케이크", "산호빛 케이크, 창밖에 모인 물고기",
             "A coral-colored birthday cake with a single candle shaped like the number 1 is placed before the baby inside the bubble dome while fish gather outside. Slow push-in."),
            (5, "해파리 조명쇼", "해파리가 무지개빛으로 반짝",
             "Glowing jellyfish outside the dome light up in rainbow colors like a party light show; the baby claps. Wide shot."),
            (3, "돌고래 축하", "돌고래들이 돔 주위를 돌며 춤",
             "Dolphins leap and swim in a circle around the dome as if dancing for the birthday. Tracking shot."),
            (5, "졸린 아기", "조개 베개에 기대 하품",
             "The baby yawns sleepily, resting on a seashell pillow as soft blue light flickers. Close-up, slow dolly."),
            (1, "수면 위로", "햇살을 향해 떠오르는 잠수함",
             "The submarine rises toward the bright surface through sun rays, bubbles trailing behind. Camera looks up from below."),
            (1, "엔딩", "노을 바다와 무지개, 제목 공간",
             "The submarine pops up on a calm sea at sunset with a rainbow in the sky; slow aerial pull-back, leaving space for a title."),
        ],
    },
    {
        "id": "forest",
        "name": "숲속 동물 친구들의 생일파티",
        "mood": "귀여움, 포근함",
        "style": "cozy storybook forest, soft warm light filtering through leaves, realistic cute animals, gentle and magical, warm color palette",
        "clips": [
            (1, "숲속 오두막", "햇살 드는 숲속 빈터의 작은 집",
             "Wide establishing shot of a small wooden cottage in a sunlit forest clearing with wildflowers and drifting butterflies. Slow push-in."),
            (5, "문 밖으로 빼꼼", "동그란 문으로 얼굴을 내밂",
             "The baby in a soft knitted outfit peeks out of the cottage's round door, blinking at the sunshine. Medium shot."),
            (1, "토끼 친구", "하얀 토끼가 손 냄새를 맡음",
             "A fluffy white bunny hops up and sniffs the baby's hand; the baby laughs. Low angle close-up."),
            (3, "아기곰의 산딸기", "아기곰이 산딸기 바구니를 가져옴",
             "A baby bear cub carries a basket of berries toward the baby and sits down beside the baby. Medium shot."),
            (5, "파티 준비", "다람쥐들이 가랜드와 등을 매닮",
             "Squirrels hang paper bunting and small lanterns between tree branches, busy preparing a party. Wide shot, camera tilts up."),
            (3, "꽃 선물", "여우와 아기사슴이 꽃을 놓고 감",
             "A little fox and a fawn bring flowers and place them in front of the baby. Medium shot, soft backlight."),
            (5, "이끼 둥지", "무릎 위에 토끼, 꽃 둥지에 앉음",
             "The baby sits in a nest of moss and flowers while a bunny rests on the baby's lap. Close-up."),
            (1, "나뭇잎 왕관", "동물들이 나뭇잎 왕관을 씌워 줌",
             "The animals place a crown of green leaves and small flowers on the baby's head; the baby smiles proudly. Close-up, slow push-in."),
            (5, "산딸기 나눠 먹기", "볼에 산딸기즙, 아기곰과 나눔",
             "Close-up of the baby and the bear cub sharing berries, berry juice on the baby's cheeks."),
            (3, "새들의 노래", "가지 위 새들을 보며 박수",
             "Birds sing on a branch above the baby while the baby looks up and claps. Medium shot."),
            (1, "숲속 케이크", "그루터기 위 숫자 1 초, 반딧불 시작",
             "Dusk: a forest birthday cake decorated with berries and flowers and a single candle shaped like the number 1 sits on a tree stump in front of the baby while fireflies begin to glow. Slow dolly-in."),
            (1, "반딧불 축하", "촛불이 꺼지며 반딧불 수백 마리가 솟음",
             "The candle goes out and hundreds of fireflies rise into the air around the baby and the animals. Wide shot, slow motion."),
            (5, "동그랗게 춤", "등불 아래 동물들과 흔들흔들",
             "The animals and the baby sit in a circle on the grass, swaying to music under glowing lanterns. Circular tracking shot."),
            (3, "아기곰에 기대 잠들기", "별 아래 아기곰에 기대어 잠듦",
             "The baby falls asleep leaning on the soft bear cub while the bunny curls up nearby under the stars. Close-up, soft night light."),
            (5, "부엉이", "보름달 앞 부엉이가 지켜봄",
             "An owl on a branch watches over them, blinking slowly, a full moon behind it. Medium shot."),
            (1, "엔딩", "반딧불 가득한 밤 숲, 제목 공간",
             "Wide shot of the glowing forest clearing at night with fireflies and a starry sky; the camera slowly rises above the trees, leaving space for a title."),
        ],
    },
    {
        "id": "patissier",
        "name": "꼬마 파티시에",
        "mood": "달콤, 발랄",
        "style": "bright candy-colored dessert world, soft pastel palette, glossy textures, playful miniature scale, cheerful lighting",
        "clips": [
            (1, "디저트 세상", "생크림 언덕, 딸기 바위, 쿠키 길",
             "Wide shot of a giant dessert world: hills of whipped cream, strawberry boulders, chocolate rivers and cookie roads under a pastel sky. Slow aerial push-in."),
            (3, "마카롱 위의 셰프", "작은 셰프 모자와 앞치마",
             "The baby in a tiny white chef hat and apron sits on a giant macaron, looking around with delight. Medium shot."),
            (5, "생크림 맛보기", "생크림에 손가락 쿡, 표정 변화",
             "Close-up: the baby pokes a finger into a huge mound of whipped cream, tastes it, makes a funny face and then smiles."),
            (1, "쿠키 계단", "셰프 모자 쓰고 쿠키 계단을 기어오름",
             "The baby in a tiny chef hat crawls up a staircase made of giant cookies, each step crunching softly. Low angle tracking shot."),
            (5, "스프링클 비", "하늘에서 스프링클이 비처럼",
             "Colorful sprinkles rain gently from the sky like confetti while the baby catches them with open hands. Slow motion, medium shot."),
            (3, "초콜릿 미끄럼틀", "초콜릿 미끄럼틀로 마시멜로 더미에",
             "The baby slides down a smooth chocolate slide into a pile of soft marshmallows, giggling. Side angle."),
            (5, "거대한 딸기", "몸만 한 딸기를 꼭 안음",
             "Close-up of the baby hugging a strawberry as big as the baby's body, green leaves on top."),
            (1, "크림 젓기", "큰 나무 주걱으로 분홍 크림 젓기",
             "The baby in a chef hat stirs a giant mixing bowl of pink frosting with a big wooden spoon, frosting splashing playfully. Medium shot."),
            (5, "사탕 꽃", "사탕 꽃이 빠르게 피어남",
             "Close-up time-lapse of candy flowers blooming open around the baby."),
            (3, "케이크 꾸미기", "작은 손으로 딸기를 올림",
             "The baby carefully places strawberries on top of a cake with tiny hands, very focused. Close-up, shallow depth of field."),
            (1, "케이크 꼭대기", "높은 케이크 위, 숫자 1 초가 켜짐",
             "The baby sits on top of a tall layered birthday cake as a candle shaped like the number 1 lights up beside the baby. Wide shot, slow crane up."),
            (3, "스프링클 불꽃놀이", "촛불이 꺼지며 스프링클이 폭죽처럼",
             "The candle goes out and colorful sprinkles burst into the air like fireworks around the baby. Medium shot, slow motion."),
            (5, "젤리곰 친구들", "젤리곰들이 케이크 주위를 돌며 춤",
             "Gummy bear friends dance in a circle around the cake where the baby sits. Wide shot."),
            (5, "막대사탕", "끈적한 볼로 막대사탕 핥기",
             "Close-up of the baby licking a big swirl lollipop, cheeks sticky, laughing."),
            (1, "코에 묻은 크림", "코에 크림 묻히고 손 흔들기",
             "The baby waves from the top of the cake with a dab of frosting on the nose. Medium close-up."),
            (1, "엔딩", "솜사탕빛 노을, 제목 공간",
             "Wide shot of the dessert world at sunset in cotton-candy colors; the camera pulls back, leaving space for a title."),
        ],
    },
    {
        "id": "retro",
        "name": "레트로 필름 앨범",
        "mood": "향수, 부모 세대 감성",
        "style": "1990s home video camcorder look, VHS grain and slight color bleed, warm faded colors, soft light leaks, nostalgic family film, no on-screen date stamp",
        "clips": [
            (1, "비디오테이프 시작", "지직거림 후 90년대 거실",
             "Opening styled like an old VHS tape: static flickers, then clears to reveal a cozy 1990s living room with patterned wallpaper, a wooden TV cabinet and afternoon sunlight. Handheld camera."),
            (5, "캠코더 켜기", "빨간 불 깜빡, 빛샘",
             "Close-up of a retro camcorder being switched on, its red light blinking, warm light leaks sweeping across the frame."),
            (1, "풍선 속 아기", "꽃무늬 카펫 위에서 카메라 보며 웃음",
             "The baby sits on a floral patterned carpet surrounded by colorful balloons, looking at the camera and laughing. Handheld medium shot, slight zoom in."),
            (3, "보행기", "90년대 보행기로 소파에 콩",
             "The baby rides a classic 1990s baby walker across the wooden floor and bumps gently into a sofa. Handheld tracking shot."),
            (5, "옛날 장난감", "나무 실로폰과 양철 장난감",
             "The baby plays with a vintage wooden xylophone and tin toys on the floor. Top-down handheld shot."),
            (3, "아기 의자 식사", "레트로 식탁의자에서 이유식",
             "The baby sits in a retro high chair eating from a plastic bowl with a spoon, food on the cheeks. Handheld medium close-up."),
            (5, "낮잠", "햇살 드는 소파, 꽃무늬 담요",
             "The baby naps on a floral blanket on a sunny sofa with dust particles floating in the sunlight. Slow handheld pan."),
            (1, "옛날 생일상", "고깔모자와 생크림 케이크",
             "A retro birthday table with a cream cake, colorful paper cone hats and a single candle; the baby sits in front wearing a paper party hat. Handheld slow zoom."),
            (3, "촛불 끄기", "박수와 색종이, 테이프 흔들림",
             "The candle goes out, blurred hands clap and confetti falls while the image flickers slightly like old tape. Medium shot."),
            (5, "선글라스 패션", "큰 선글라스와 벙거지",
             "The baby tries on oversized sunglasses and a bucket hat, looking funny and serious. Handheld close-up."),
            (5, "놀이터 스프링 말", "스프링 말을 타고 흔들흔들",
             "An outdoor 1990s playground: the baby rocks back and forth on a small spring rider horse. Handheld medium shot, warm faded sunlight."),
            (3, "안아 줘", "두 팔 벌리고 카메라로 걸어옴",
             "The baby toddles toward the camera with open arms across a sunlit yard. Handheld, slight zoom out as the baby approaches."),
            (5, "앨범 넘기기", "빈 사진 틀이 빛남 (실제 사진 합성용)",
             "Close-up of old photo album pages turning slowly, with empty photo frames glowing softly."),
            (1, "현재로", "테이프 되감기 → 요즘 밝은 거실",
             "The tape rewinds with a flicker transition and the room becomes a bright modern living room; the same baby sits there smiling. Seamless transition."),
            (1, "손 키스", "요즘 화질로 손 키스 → 다시 VHS",
             "Close-up: the baby blows a kiss toward the camera in clean modern light, then the image softly returns to VHS grain."),
            (1, "엔딩", "옛날 TV 지직 → 따뜻한 흰 화면",
             "An old TV screen in the living room shows static, then fades to warm white, leaving space for a title."),
        ],
    },
    {
        "id": "balloon",
        "name": "열기구 꿈나라 여행",
        "mood": "서정적, 여유",
        "style": "dreamy soft painterly look, pastel sky gradients, gentle lens flares, peaceful and airy, storybook cinematic",
        "clips": [
            (1, "창가의 낮잠", "종이 열기구 모빌 아래 낮잠",
             "The baby naps by a sunny window under a slowly turning mobile of paper hot-air balloons. Slow push-in."),
            (3, "모빌이 진짜로", "종이 열기구가 빛나며 진짜로 커짐",
             "One paper balloon from the mobile glows and grows into a real colorful hot-air balloon outside the window. Wide shot, magical transformation."),
            (1, "이륙", "무지개 열기구 바구니에서 웃음",
             "The baby sits in the wicker basket of a rainbow-striped hot-air balloon, holding the edge and smiling as it lifts off from a green hill. Medium shot."),
            (5, "구름 만지기", "지나가는 구름을 손으로",
             "Close-up of the baby's hands touching a passing puffy cloud that feels soft like cotton; the baby giggles."),
            (3, "장난감 마을 위", "알록달록 지붕 위를 둥실",
             "Wide aerial shot of the balloon floating over a small toy-like town with colorful rooftops. Slow tracking shot."),
            (5, "새 떼", "하얀 새들이 옆에서 함께 날아감",
             "A flock of white birds flies alongside the basket while the baby points at them excitedly. Medium shot."),
            (1, "설산의 아침", "분홍빛 설산 봉우리를 지나감",
             "Wide aerial shot of the balloon gliding past snowy mountain peaks glowing pink at sunrise."),
            (5, "폭포와 무지개", "물안개 무지개에 손 뻗기",
             "The balloon passes a waterfall with a small rainbow in the mist; the baby reaches toward the rainbow. Medium shot."),
            (3, "무지개 통과", "무지개 아치를 통과, 얼굴에 색이 비침",
             "The balloon floats through a big rainbow arch, its colors reflecting on the baby's face. Slow motion."),
            (5, "열기구 친구들", "파스텔 열기구들이 함께 떠다님",
             "Other small pastel hot-air balloons float nearby in the sky like friends. Wide shot."),
            (1, "노을 생일", "바구니 안 숫자 1 초 케이크",
             "At sunset a small birthday cake with a single candle shaped like the number 1 sits in the basket; the baby gazes at the flame in golden light. Close-up, slow push-in."),
            (3, "밤하늘", "별이 뜨고 열기구가 따뜻하게 빛남",
             "Night falls, stars appear and the balloon glows warmly while the baby looks up at the starry sky. Wide shot."),
            (5, "별똥별", "별똥별에 박수",
             "Shooting stars streak across the sky and the baby claps. Medium shot."),
            (5, "초승달 착륙", "초승달에 내려앉아 손 흔들기",
             "The balloon lands softly on a crescent moon and the baby waves from the basket. Wide shot."),
            (1, "꿈에서 깸", "열기구 인형을 안고 깨어나 미소",
             "Back in the bedroom, the baby wakes up hugging a small plush hot-air balloon and smiles. Slow dolly-in."),
            (1, "엔딩", "별밤 마을 위로 멀어지는 열기구",
             "Wide shot of the rainbow balloon drifting away into a starry sky over the sleeping town, leaving space for a title."),
        ],
    },
    {
        "id": "awards",
        "name": "첫돌 영화 시상식",
        "mood": "유쾌, SNS 공유용",
        "style": "glamorous award-show look, warm spotlights, golden and red color palette, lens flares, cinematic shallow depth of field, playful and funny",
        "clips": [
            (1, "레드카펫", "밤의 극장 입구, 금빛 조명",
             "Wide shot of a glamorous theater entrance at night with a red carpet, velvet ropes, golden lights and a crowd of blurred silhouettes. Slow push-in."),
            (5, "리무진 도착", "장난감 같은 리무진 문이 열림",
             "A small toy-like limousine pulls up to the red carpet and its door opens slowly. Low angle shot."),
            (1, "레드카펫 입장", "턱시도(또는 드레스), 플래시 세례",
             "The baby in a tiny tuxedo crawls confidently down the red carpet as camera flashes pop. Low tracking shot, slow motion."),
            (3, "스타의 눈빛", "멈춰서 진지한 표정으로 카메라 응시",
             "The baby pauses on the red carpet and looks at the cameras with a serious star face while flashes go off. Medium close-up."),
            (5, "선글라스", "작은 선글라스 끼고 손 흔들기",
             "The baby wears tiny sunglasses and waves to the crowd like a celebrity. Close-up."),
            (3, "시상식장", "스포트라이트와 금빛 커튼",
             "Inside a grand theater hall, spotlights sweep across the stage and a big golden curtain. Wide shot."),
            (5, "객석", "빨간 벨벳 의자에서 다리 달랑달랑 박수",
             "The baby sits in a plush red velvet chair in the front row, legs dangling, clapping. Medium shot."),
            (1, "수상자 발표", "스포트라이트가 아기에게, 꽃가루",
             "A spotlight lands on the baby and confetti falls as if the baby has just been announced as the winner. Wide shot, slow crane."),
            (3, "트로피 받기", "숫자 1 모양 금색 트로피",
             "The baby is carried onto the stage and receives a golden trophy shaped like the number 1, holding it with both hands. Medium shot."),
            (5, "트로피 깨물기", "트로피를 깨물어 보고 웃음",
             "Close-up of the baby trying to bite the trophy, then laughing."),
            (1, "기립박수", "트로피를 번쩍, 금빛 꽃가루",
             "The baby holds a golden number 1 trophy high as golden confetti and streamers fall and blurred silhouettes give a standing ovation. Medium shot, slow motion."),
            (3, "백스테이지 케이크", "꽃다발 사이 숫자 1 초 케이크",
             "Backstage, a birthday cake with a single candle shaped like the number 1 is brought to the baby among bouquets of flowers. Medium shot."),
            (5, "포토월", "금빛 배경 앞에서 트로피 들고 포즈",
             "The baby poses with the trophy in front of a golden backdrop while photographers' flashes go off. Close-up, rapid flashes."),
            (5, "무대 위 댄스", "색색 조명 아래 신나게 춤",
             "The baby dances happily on the stage under colorful spotlights. Wide shot."),
            (1, "손 키스 인사", "관객에게 손 키스와 손 흔들기",
             "The baby blows a kiss to the audience and waves goodbye. Close-up."),
            (1, "엔딩", "커튼이 닫히고 빈 무대에 조명 (크레딧 공간)",
             "The theater curtain slowly closes, then a warm spotlight lights the empty stage, leaving space for end credits. Wide shot."),
        ],
    },
]

# 길이별 구성: (사진 구간 길이 초 목록, 각 사진 구간을 넣을 위치 = 몇 번째 AI 장면 뒤)
VERSIONS = {
    1: {"label": "1분", "tiers": (1,), "photo_blocks": [12], "after": [3]},
    3: {"label": "3분", "tiers": (1, 3), "photo_blocks": [50, 50], "after": [3, 7]},
    5: {"label": "5분", "tiers": (1, 3, 5), "photo_blocks": [58, 57, 57], "after": [4, 8, 12]},
}
